---
name: Release - Build and Test

on:
  release:
    types: [published]

env:
  REGISTRY_IMAGE: ghcr.io/rit4lin/receipt-wrangler

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: golang:1.25-trixie
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Mark workspace as safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install app dependencies
        run: sh set-up-dependencies.sh
        working-directory: ./api
      - name: Build
        run: go build -v ./...
        working-directory: ./api
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -v ./...
        working-directory: ./api
      - name: Upload Coverage Report to Codecov
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./api/coverage.out
          flags: api
          fail_ci_if_error: true
          verbose: true
      - name: Test imap client
        run: |
          . wranglervenv/bin/activate
          python3 -m unittest discover -s ./imap-client
        working-directory: ./api

  test-desktop:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GH_PACKAGE_READ_TOKEN_DESKTOP: ${{ secrets.GH_PACKAGE_READ_TOKEN_DESKTOP }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"
      - name: Install dependencies
        run: npm ci --verbose
        working-directory: ./desktop
      - name: Run tests
        run: npm run test:ci
        working-directory: ./desktop
      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: desktop/coverage/receipt-wrangler-desktop/cobertura-coverage.xml
          format: markdown
          output: both
          badge: true
      - name: Upload coverage to Codecov
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./desktop/coverage/receipt-wrangler-desktop/cobertura-coverage.xml
          flags: desktop
          fail_ci_if_error: true

  build-docker-arm64:
    needs: [test-api, test-desktop]
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Build and push ARM64
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          platforms: linux/arm64
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}-arm64
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=${{ steps.date.outputs.date }}

  build-docker-amd64:
    needs: [test-api, test-desktop]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Build and push AMD64
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          platforms: linux/amd64
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}-amd64
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=${{ steps.date.outputs.date }}

  create-docker-manifest:
    needs: [build-docker-arm64, build-docker-amd64]
    if: |
      always() &&
      needs.build-docker-arm64.result == 'success' &&
      needs.build-docker-amd64.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Multi-Arch Manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}
          sources: |
            ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}-amd64
            ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}-arm64
